org: '1253546688'
app: notion-nice
stage: prod
component: layer
name: notion-nice-layer
inputs:
  name: notion-nice-layer
  region: ap-guangzhou
  src:
    src: ../node_modules
    targetDir: /node_modules
  runtimes:
    - Nodejs12.16
